/**:
  turtlebot4_node:
    ros__parameters:
      wifi:
        interface: "wlan0"
      power_saver: false
      buttons:
        create3_1: ["Dock", "Wall Follow Left", "2000"]
        create3_power: ["EStop", "Power", "3000"]
        create3_2: ["Undock", "Wall Follow Right", "2000"]
        hmi_1: ["Select"]
        hmi_2: ["Back"]
        hmi_3: ["Scroll Up"]
        hmi_4: ["Scroll Down"]
      menu:
        entries: ["Dock", "Undock", "EStop", "Wall Follow Left", "Wall Follow Right", "Power", "Help"]
      controller:
        b: ["EStop"]
        a: ["Select"]
        x: ["Back"]
        up: ["Scroll Up"]
        down: ["Scroll Down"]
        l2: ["Wall Follow Left"]
        r2: ["Wall Follow Right"]
        home: ["Dock", "Undock", "3000"]